spring.application.name=campuseatsOrders

server.port=8080

# Payments service URL comes from environment variable
payments.base-url=${PAYMENTS_URL:http://localhost:8082}

# Actuator
management.endpoints.web.exposure.include=health,info